version: "2"

services:

  app:

    image: node:9.10
    working_dir: /app
    container_name: zabana_api
    volumes:
      - .:/app
    environment:
      PORT: "8181"
    expose:
      - "8181"
    ports:
      - "3000:8181"
    links:
      - database
    command: bash -c "npm install -g nodemon && nodemon app.js"

    ## This makes sure that database runs BEFORE myapp so that we have a
    # connection open when the server is started
    depends_on:
      - database

  database:
    container_name: zabana_api_db
    image: mongo
    # Adds data persistence across builds / restarts
    volumes:
      - ./data/db:/data/db
